[versions]

paper = "26.3.build.159-beta"

[libraries]

# Not used in the project but declared here for Renovate
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

[plugins]

paperweight-userdev = { id = "io.papermc.paperweight.userdev", version = "2.0.0-beta.24" }
run-paper = { id = "xyz.jpenilla.run-paper", version = "3.1.0" }
jcommon = { id = "dev.siroshun.gradle.plugins.jcommon", version = "1.8.6" }
